version: '3.3'

services:
  go-dmux:
    build:
      context: ./..
      dockerfile: docker/Dockerfile
    volumes:
      - ${PWD}/config/conf.json:/etc/go-dmux/config.json
    command: ["/etc/go-dmux/config.json"]
    ports:
      - "1234:1234"
    depends_on:
      - "event-server"
      - "kafka"
      - "zookeeper"
    restart: always
  event-server:
    build:
      context: ./..
      dockerfile: docker/Dockerfile-event-server
    ports:
      - "8888:8888"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-2.0.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181/kafka
      KAFKA_CREATE_TOPICS: "sample-topic:1:1"
      KAFKA_ADVERTISED_HOST_NAME: 192.168.86.153
    depends_on:
      - "zookeeper"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock